server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config_repo/eureka,file:./config_repo/zuul,file:./config_repo/licensingservice,file:./config_repo/organizationservice,file:./config_repo/authservice,file:./config_repo/zipkinservice