server:
  port: 8901
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/auth
    username: uca
    password: password
logging:
  level:
    org:
      hibernate: debug