server:
  port: 7010
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jooq:
    sql-dialect: mysql_8_0
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/file
    username: uca
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.63.195
    port: 6379