server:
  port: 7010
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  jooq:
    sql-dialect: mysql_8_0
  datasource:
    url: jdbc:mysql://192.168.63.195:3306/file
    username: uca
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.63.195
    port: 6379
  resources:
    static-locations: file:${uca.fileserver.real-file-path},file:${uca.fileserver.temp-file-path}
uca:
  fileserver:
    url: http://localhost:7010
    real-file-path: /opt/uca/file
    temp-file-path: /opt/uca/temp
security:
  oauth2:
    resource:
      user-info-uri: http://gwserver/authserver/user
    client:
      grant-type: client_credentials